analytics: {}
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 1
  lightness: 0.29054
  rhythmicContrast: 0.77027
  saturation: 0.886764
cta: {}
layout_spectrum: 0.030405
name: DBranded Photography
opengraph: {}
purpose: []
typography_spectrum: 0.608108
