analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d4d4d4'
    - '#333333'
    - '#7b7b7b'
  brandStrength: 0.656531
  lightness: 0.4375
  rhythmicContrast: 0.77027
  saturation: 0
cta: {}
layout_spectrum: 0.407657
name: DBranded Photography
opengraph: {}
purpose: []
typography_spectrum: 0.55196
