analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d4d4d4'
    - '#333333'
    - '#7b7b7b'
  brandStrength: 0
  lightness: 0.487612
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.997747
name: DBranded Photography
opengraph: {}
purpose: []
typography_spectrum: 0.55196
