analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d4d4d4'
    - '#333333'
    - '#7b7b7b'
  brandStrength: 0.983108
  lightness: 0.996621
  rhythmicContrast: 0.986486
  saturation: 0.987612
cta: {}
layout_spectrum: 0.997747
name: DBranded Photography
opengraph: {}
purpose: []
typography_spectrum: 0.55196
