name: DBranded Photography
favicon: null
layout_spectrum: 0.030405
typography_spectrum: 0.608108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d4d4d4'
    - '#333333'
    - '#7b7b7b'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.77027
purpose: []
